BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXX XXXXXX XXXXXXXXXXXX XXXX XXXX X XXXX XXXXXXXX XXX XX XXXXXXXX XXX XXX XXXXXX XXXX XX XXXXXXXX XXX XXXX XXXX XXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXX XXXXXXXXXX

    XXXXX XXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX

    XXXXXXXXXX XXXX XXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB BBB
    BBBBBBBB

    BBBBB BBBBBBB
    BBBBBBBB
  XXXXXXX
  XXXXXX

    XXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX
    XXXXXXXXX

    XXXXX XXXXXXXXXXXX
      BBBBB BBBBBBB

      BBBBBBBB

      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX

    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX     XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXXXXXXXXXXXX
    XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
      XXX
    XXXXXXXXX

    BBBBB BBBBBBB

    BBBBBBBB
  XXXXXXX
XXXXXXX
