# Generated by Django 2.0 on 2017-12-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('quote', models.TextField()),
            ],
        ),
    ]
