# Generated by Django 2.0 on 2017-12-16 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('quote', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.IntegerField(default=2017, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2017)])),
                ('is_admin', models.BooleanField(default=False)),
                ('account_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
