# Generated by Django 2.0 on 2018-01-16 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Enter your full name', max_length=100)),
                ('email', models.EmailField(help_text='Enter your email, eg. rishikesh0014051992@gmail.com', max_length=100, unique=True)),
                ('contact', models.CharField(help_text='Enter your 10 digit mobile number', max_length=10)),
                ('dob', models.DateField(blank=True, help_text='Enter your date of birth', null=True)),
                ('password', models.CharField(help_text='Enter your password', max_length=20)),
                ('quote', models.TextField(blank=True, help_text='Enter your popular quote, eg. Never give up and try to achieve your goal with passion', null=True)),
                ('batch', models.IntegerField(default=2018, help_text='From which batch(admission year) you are, eg. 2018, 2015, 2011 etc.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('is_admin', models.BooleanField(default=False, help_text='Hi Admin, do you really want to make this person as an admin?')),
                ('is_active', models.BooleanField(default=False, help_text='Hi Admin, do you really want to make this person a PMT member?')),
                ('account_confirmed', models.BooleanField(default=False, help_text='User has confirmed his account or not')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when user registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time when he updated the details')),
            ],
        ),
    ]
