# Generated by Django 2.0 on 2018-01-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmt_hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ppic',
            field=models.CharField(blank=True, default='', help_text='Name of pic inside media root', max_length=1000),
        ),
    ]
